name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl

      - name: Move kubectl to /usr/local/bin
        run: |
          sudo mv kubectl /usr/local/bin/

      - name: Get CCE Cluster Credentials
        uses: huaweicloud/cce-credential-action@v1.0.0
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "eecc7ec81ad346adbcde0a07fa343cb0"
          cluster_id: "36aae077-e83f-11ee-b54e-0255ac100750"

      - name: Get CCE Cluster Info
        run: |
          kubectl cluster-info
          kubectl get pod,svc --all-namespaces
