name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branches

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: get CCE Cluster Credentials
        uses: huaweicloud/cce-credential-action@v1.0.1
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "3e7cb44b-4b49-43b5-93df-d78f8a24e2dc"
          cluster_id: "974f91d7-8457-11ee-b946-0255ac100753"
          
      - name: Debugging
        run: |
          kubectl cluster-info
          kubectl get nodes
   
