name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: 'af-south-1'

      - name: Set up KooCLI
        uses: huaweicloud/huaweicloud-cli-action@v1.0.3

      - name: Show Specific Version Info of ECS by KooCLI
        run: 'hcloud CCE CreateKubernetesClusterCert --cli-region="af-south-1" --Content-Type="application/json" --cluster_id="36aae077-e83f-11ee-b54e-0255ac100750" --duration=100'      

      - name: Get CCE Cluster Info
        run: |
          kubectl cluster-info
