name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl for Huawei Cloud CCE
        run: |
          sudo mkdir -p $HOME/.kube
          sudo chown -R runner:runner $HOME/.kube
          export KUBECONFIG=$HOME/.kube/config
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $KUBECONFIG
      

      - name: Debugging
        run: |
         
          kubectl cluster-info
          kubectl get nodes


